name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Code autoformatting
      run: ./gradlew spotlessApply
      
    - name: Commit code autoformatting
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Code formatting [skip ci] [version]
        
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease
      
    - name: Run unit tests
      run: ./gradlew testReleaseUnitTest
